### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by LCAdmin** [AddstarMC/BlockHunt#10]
Is adding support for giving player's a cash reward in your to-do list or is it a feature I've overlooked?

**Comment by LCAdmin** [comment]
If you like, we could add this feature if you updated the source code on github?

**Comment by alchemistmatt** [comment]
BlockHunt source code is up-to-date (for the AddstarMC fork of the original BlockHunt).  Our last commit to master was August 5: [56f0844](https://github.com/AddstarMC/BlockHunt/commits/master).  You can fork that version, update the code, then submit a pull request and we will review it.

**Comment by addstar** [comment]
@LCAdmin: Also, this wasn't really overlooked, just wasn't something we really needed at the moment. It was on a list to do someday, but who knows when that could be :smirk: 

If you're keen to do it, feel free to make submit a PR, but it would need per-arena reward values.

**Comment by LCAdmin** [comment]
I've never really used Github before, so could you guys give me some tips on getting the source code and compiling it for tests?

**Comment by alchemistmatt** [comment]
Go to https://github.com/AddstarMC/BlockHunt then click "Fork" on the upper right.  Create the forked copy in your repository (i.e. the repo that has your "Random-Things" project).  Next, on your local desktop, you clone the project using url https://github.com/LCAdmin/BlockHunt (created by the fork) or https://github.com/BlockHunt.git (which to use may depend on your Git client).  

For more info, see https://help.github.com/articles/fork-a-repo/
