### ISSUE TITLE
Hiders do no damage

### ISSUE THREAD

**Issue by cmburcus** [AddstarMC/BlockHunt#11]
I've been looking for the reason this is happening forever but i couldn't figure it out. PvP is allowed (although i had to search so much what was going on before fixing that. Not an issue with BH).

commit 56f0844e1cbd4862f7ef00f58095c069416c614b
According to the above commit (#30 (Aug 5, 2015 9:46:40 PM)), seekers cannot be damaged by hiders. Is there a reason to this? I know this build is a custom one and from what i gathered it was tweaked a bit but i'd like to know if there is a way around it (other than going to version #29).

The commit name says :Fix seeker damage always being cancelled but it seems to still be on for when hiders attack seekers.

Thank you very much for taking the time to read this.

**Comment by addstar** [comment]
Sorry, but I'm not sure I understand what you are trying to say.

Are you saying that when you use build 30, hiders are unable to hurt seekers? Did you make sure you had the `hidersCanHurtSeekers` option enabled?

Prior to 56f0844e1cbd4862f7ef00f58095c069416c614b, there was a bug which prevented seekers from receiving damage. This commit fixed that issue so it seems the opposite of what you are saying.

Can you clarify?

**Comment by cmburcus** [comment]
Hey thank you for your reply.

I was trying to make sense of the code around the commit. I didn't try build 29 yet but on build 30, hiders cannot hurt seekers (at least not on my server). I have tested pvp and it is definitely on (especially because seekers can hurt hiders).

I was tired when i reviewed the code, i probably got confused.

Anyhow. So yes, hiders cannot hurt seekers on my server. I've been trying to find an option (such as hidersCanHurtSeekers) but I could not find it either in the config or as a command :/ let me know if any additional info would be helpful for this. Like me pasting my config or anything.

**Comment by addstar** [comment]
You need to enable it in the config file and restart. Unfortunately, I didn't bother making an in-game command to change these settings.

Please see this commit (1e38bd6b2970ab3354417cff2eff116509a4c709) description for the details.

In your case, you need to enable `hidersCanHurtSeekers` which is disabled by default.

**Comment by cmburcus** [comment]
You saved my life. Thank you very much !

**Comment by addstar** [comment]
No problem, glad it's working for you now :smile:
