### ISSUE TITLE
Seekers Please add ability to kill

### ISSUE THREAD

**Issue by jalamaac** [AddstarMC/BlockHunt#13]
you cant kill seekers i cant edit code and compile missing dependency can you upload new complied to jerkins please

**Comment by jalamaac** [comment]
added the lines to the config still no luck

**Comment by addstar** [comment]
You need to edit your arenas.yml. Please see this commit for more information.
https://github.com/AddstarMC/BlockHunt/commit/1e38bd6b2970ab3354417cff2eff116509a4c709
