### ISSUE TITLE
Player Disconnect

### ISSUE THREAD

**Issue by CoolLord22** [AddstarMC/BlockHunt#22]
If a player disconnects, then they're taken out of the game. However, when they reconnect they still spawn inside of the arena. Is there a way to handle their reconnect to either put them back in the game (if its still running) or take them to the lobby?

**Comment by CoolLord22** [comment]
Took it into my own hands actually and figured out the fix! If you'd like to add it into the plugin, just change the OnPlayerQuitEvent.java because the rest of the changes are meant for my actual server. https://github.com/CoolLord22/BlockHunt/commit/ed36764386f6bd5854bbdc63ae58416f89fca194#diff-b31efc9d8c2649dfc2a844021e15d901

**Comment by alchemistmatt** [comment]
Thank you for your contribution. We have integrated your improvements into the codebase: https://github.com/AddstarMC/BlockHunt/compare/c774bcd38366...af72f0d82967
