### ISSUE TITLE
Download link ? :D

### ISSUE THREAD

**Issue by TheIntelloBox** [AddstarMC/BlockHunt#26]
Hey ! :D 

Where can I download the latest dev build of BlockHunt ? :D 

Have a nice morning or day or evening or night ! :D 
Thanks ! :D 
TheIntelloBox ! :D

**Comment by Narimm** [comment]
There will not be a new dev build until I have changed and all the deps have 1.13 capable versions

**Comment by L27SlubbyGames** [comment]
Thx.
