### ISSUE TITLE
Memory leak (maybe since 1.18's)

### ISSUE THREAD

**Issue by TNTUP** [AddstarMC/BlockHunt#66]
My minigame server which was on 1.17.1 didn't have this issue but today I've upgraded it to 1.18.2 (it was my last server to update because another plugin which the server depend got updated last week) but currently the server been crashing because it was mem leaking by BlockHunt.Managers.ConfigManager ?? Screenshot below

![oof](https://i.qcfb.ca/20220408031158.png)

Paper 1.18.2 #278 
BlockHunt 0.5.0 #50

**Comment by addstar** [comment]
Wow... that's definitely not right! I really appreciate the heap dump analysis on this.. it will make it a lot easier to find the problem :grinning: 

Yeah it's definitely one of these: https://github.com/AddstarMC/BlockHunt/blob/master/src/main/java/nl/Steffion/BlockHunt/MemoryStorage.java#L38 but finding the cause will take a bit more work.

Some questions for you:
1. Does this just happen with normal game usage?
2. Do you ever reload the config live?
3. Approximately how long did it take to get to this point? (hours/days/weeks)

**Comment by TNTUP** [comment]
Take your time^^ If you want the heapdump, its over 6GB in size (will be uploaded on my server) let me know^^

1. Can't tell, server is inactive (idle)
2. Nope
3. Since 2 days ago I updated the server to 1.18.2, server crashes due to memory leak then restarts (I'm using a panel so it'll restarts when it detects a crash) and it'll crash maybe again a few hours

**Comment by TNTUP** [comment]
Heya there, been like 2-3 months. Are you still interested by fixing if you can xD (I'm aware that you have a busy life, work...)?
But.. if this project is long dead, I'll close the issue due to inactivity XD

PS: I still have the heap file if needed before I delete it^^

**Comment by TNTUP** [comment]
Closing as my server going to be shutdown next year in Jul 2023
